spring:
  application:
    name: spring-security-6
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#  security:
#    user:
#      name: manu
#      password: password

logging:
  level:
    com.dailycodebuffer.security: DEBUG
    org:
      springframework:
        security: TRACE
        web:
          csrf: TRACE
          header: TRACE
        access: DEBUG